name: Deploy Synapse Workspace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print path
        run: ls -R
      - name: Deploy Synapse Workspace
        uses: Azure/Synapse-workspace-deployment@V1.8.0
        with:
          TargetWorkspaceName: 'synapseprodyash'
          TemplateFile: './TemplateForWorkspace.json'
          ParametersFile: './TemplateParametersForWorkspace.json'
          environment: 'Azure Public'
          resourceGroup: 'Yash-Prod'
          clientId: ${{ secrets.AZURE_CLIENT_ID }}
          clientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenantId: ${{ secrets.AZURE_TENANT_ID }}
          operation: 'deploy'
